### ISSUE TITLE
Minor doc improvements

### ISSUE THREAD

**Issue by MichelRottleuthner** [riot-appstore/PHiLIP#51]
After I read the README, here are some remarks how the doc can be improved a bit. Just my opinion, and what popped up in my mind - so if you don't agree feel free to discuss or ignore ;)

##########################################
under "Setup of PHiLIP Environment"
the step "HINT: If flashing a nucleo-f103rb use the following command"
won't work with every OS so this should be either rephrased or removed
##########################################
General note: the overall goal of "Getting Started as a Developer" is not well
defined. I.e. it lacks "diving in from the big picture/general concept" to the
point where it is shown how things are actually done, step by step.
The steps/examples of commands look a bit arbitrarily selected. If some of the
steps are meant for showing a general concept on "how to control PHiLIP", this
should be stated explicitly.

E.g. something like: "The process of updating runtime configuration of a PHiLIP
(like X) is to execute steps A, B, and C. The following example shows this by
applying the concept to setting Z."

I think setting up the RTC is actually meant for showing something like that:

14. Manually prepare the rtc time.
...
15. Clear the rtc.mode.init bit to reinitialize and set rtc values on execute.
...
16. Execute the changes.  <<<--- e.g. why is this actually needed?
                                 What happens there? Is this required always,
                                 or only for some specific kind of settings?
...
17. Read the new RTC time.

After talking offline about this: an explicit note at the beginning on how awesome the PHiLIP help commands are would help with this ;)

##########################################
The pinout of PHiLIP-N can be improved:
for example change this:
```
PHILIP-N -> NUCLEO-F103RB
CN6                                               CN5

                            DUT_SCL = PB8 = SCL/D15 -
                            DUT_SDA = PB9 = SDA/D14 -
                                               AVDD -
                                                GND -
-                               LED0 = PA5 =SCK/D13 -
- IOREF                                    MISO/D12 -
- NRST                                 PWM/MOSI/D11 -
- 3V3                                    PWM/CS/D10 -
- 5V                                         PWM/D9 -
- GND                             DUT_TX = PA9 = D8 -
- GND
- VIN                             DUT_IC = PA8 = D7 -
                                             PWM/D6 -
- A0 = PA0 = TEST_WARN        DEBUG1 = PB4 = PWM/D5 -
- A1 = PA1 = TEST_FAIL            DEBUG2 = PB5 = D4 -
- A2 = PA4 = TEST_PASS        DEBUG0 = PB3 = PWM/D3 -
- A3 = PB0 = DUT_ADC             DUT_RX = PA10 = D2 -
- A4 = PC1 = PM_HI_ADC          IF_TX = PA2 = TX/D1 -
- A5 = PC0 = PM_V_ADC           IF_RX = PA3 = RX/D0 -


          CN8                           CN9

          -1 -                  DUT_DAC -1 - DUT_PWM
          -2 -                  DUT_SCL -2 -
          -3 -                  DUT_SDA -3 -
          -4 -                          -4 -
          -5 -                          -5 -
          -6 -                     LED0 -6 - DUT_RTS
          -7 -                          -7 - DUT_CTS
          -8 -                          -8 - DUT_NSS
          -9 -                          -9 -
          -10-                          -10-
          -11-                   DUT_TX -11- DUT_RST
 USER_BTN -12-                   DUT_IC -12-
          -13-                          -13- DUT_MOSI
          -14- TEST_WARN         DEBUG1 -14- DUT_MISO
          -15- TEST_FAIL         DEBUG2 -15- DUT_SCK
          -16- TEST_PASS         DEBUG0 -16-
          -17- DUT_ADC           DUT_RX -17-
PM_LO_ADC -18- PM_HI_ADC          IF_TX -18-
          -19- PM_V_ADC           IF_RX -19-
```
to something like this, to also include the exact pin numbers from the board manual:
```
                                                     CN5
                             DUT_SCL = PB8 = SCL/D15 10-
                             DUT_SDA = PB9 = SDA/D14  9-
                                                AVDD  8-
CN6                                              GND  7-
-1                               LED0 = PA5 =SCK/D13  6-
-2 IOREF                                    MISO/D12  5-
-3 NRST                                 PWM/MOSI/D11  4-
-4 3V3                                    PWM/CS/D10  3-
-5 5V                                         PWM/D9  2-
-6 GND                             DUT_TX = PA9 = D8  1-
-7 GND
-8 VIN                             DUT_IC = PA8 = D7  8-
                                              PWM/D6  7-
-1 A0 = PA0 = TEST_WARN        DEBUG1 = PB4 = PWM/D5  6-
-2 A1 = PA1 = TEST_FAIL            DEBUG2 = PB5 = D4  5-
-3 A2 = PA4 = TEST_PASS        DEBUG0 = PB3 = PWM/D3  4-
-4 A3 = PB0 = DUT_ADC             DUT_RX = PA10 = D2  3-
-5 A4 = PC1 = PM_HI_ADC          IF_TX = PA2 = TX/D1  2-
-6 A5 = PC0 = PM_V_ADC           IF_RX = PA3 = RX/D0  1-
CN8                                                  CN9


               CN7                                  CN10
          -1  | 1|  2-                  DUT_DAC -1  | 1|  2- DUT_PWM
          -3  | 2|  4-                  DUT_SCL -3  | 2|  4-
          -5  | 3|  6-                  DUT_SDA -5  | 3|  6-
          -7  | 4|  8-                          -7  | 4|  8-
          -9  | 5| 10-                          -9  | 5| 10-
          -11 | 6| 12-                     LED0 -11 | 6| 12- DUT_RTS
          -13 | 7| 14-                          -13 | 7| 14- DUT_CTS
          -15 | 8| 16-                          -15 | 8| 16- DUT_NSS
          -17 | 9| 18-                          -17 | 9| 18-
          -19 |10| 20-                          -19 |10| 20-
          -21 |11| 22-                   DUT_TX -21 |11| 22- DUT_RST
 USER_BTN -23 |12| 24-                   DUT_IC -23 |12| 24-
          -25 |13| 26-                          -25 |13| 26- DUT_MOSI
          -27 |14| 28- TEST_WARN         DEBUG1 -27 |14| 28- DUT_MISO
          -29 |15| 30- TEST_FAIL         DEBUG2 -29 |15| 30- DUT_SCK
          -31 |16| 32- TEST_PASS         DEBUG0 -31 |16| 32-
          -33 |17| 34- DUT_ADC           DUT_RX -33 |17| 34-
PM_LO_ADC -35 |18| 36- PM_HI_ADC          IF_TX -35 |18| 36-
          -37 |19| 38- PM_V_ADC           IF_RX -37 |19| 38-
```

##########################################
for read_struct rtc, why is there no year field?
##########################################
Under "Getting Started with CI Scripts", typos? should this:
Example of *python test script tests the trace function, connect the DUT_RST to the DEBUG0 pin.

actually be something like this:
Example of *a* python test script *that* tests the trace function.
For running this, connect the DUT_RST to the DEBUG0 pin.
##########################################
Under "Pin Descriptions"
LED0 	Heartbeat connection to bluepill LED
should be (?):
LED0 	Heartbeat connection to *PHiLIP* LED

PM_HI_ADC 	Course, mA range of current measurement (..)
should be:
PM_HI_ADC 	*Coarse*, mA range of current measurement (..)
##########################################
Under "Test Capabilities":
Test*s* should *test both*, that certain ...

SPI->Pass Cases: ensure a change has occurred  <- what does this mean? (very
                                                  unspecific)

General: the descriptions are a bit short: not clear what some of those actually
are meant to describe.

Why does ADC not have a resolution spec?
##########################################

**Comment by MrKevinWeiss** [comment]
Fixed with #52 and some irl explaining
